export const CANVAS_CONFIG = {
  ANTIALIAS: false,
  RESOLUTION: 1,
} as const

export const CLOUD_CONFIG = {
  MIN_CLOUDS: 30,
  MAX_CLOUDS: 200,
  MIN_ON_SCREEN: 25,
  MIN_SCALE: 0.3,
  MAX_SCALE: 2.0,
  SPEED_MIN: 0.01,
  SPEED_MAX: 3,
  FADE_SPEED: 0.02,
  RESPAWN_MARGIN: 400,
  SPAWN_INTERVAL_MIN: 0,
  SPAWN_INTERVAL_MAX: 5000,
} as const
